#!/usr/bin/env sh
# -----------------------------------------------------------------------------
# Copyright (c) 2018, Justine T Kizhakkinedath
# All rights reserved
#
# Licensed under the terms of MIT License
# See LICENSE file in the project root for full information.
# -----------------------------------------------------------------------------

# Behaviour: Will delete any existing python virtualenv
# create a new virtualenv
# create a new package and install inside it.
rm -rf venv
python3 -m venv venv
source venv/bin/activate
# pip install -r requirements.txt
pip-create_package
pip install ./dist/*.tar.gz
