#!/usr/bin/env sh
# -----------------------------------------------------------------------------
# Copyright (c) 2018, Justine T Kizhakkinedath
# All rights reserved
#
# Licensed under the terms of MIT License
# See LICENSE file in the project root for full information.
# -----------------------------------------------------------------------------

rm -rf venv
virtualenv venv
source venv/bin/activate
pip-create_package develop
pip install ./dist/*.tar.gz
deactivate
source venv/bin/activate
