#!/usr/bin/env sh
# -----------------------------------------------------------------------------
# Copyright (c) 2018, Justine T Kizhakkinedath
# All rights reserved
#
# Licensed under the terms of MIT License
# See LICENSE file in the project root for full information.
# -----------------------------------------------------------------------------


# source ~/python-virtualenvs/my_venv36/bin/activate
if [ "$1" != "pypi" ]; then
    ~/python-virtualenvs/my_venv36/bin/twine upload -r testpypi dist/*
else
    ~/python-virtualenvs/my_venv36/bin/twine upload -r pypi dist/*
fi
# deactivate
