#!/usr/bin/env sh
# -----------------------------------------------------------------------------
# Copyright (c) 2018, Justine T Kizhakkinedath
# All rights reserved
#
# Licensed under the terms of MIT License
# See LICENSE file in the project root for full information.
# -----------------------------------------------------------------------------


# Instruction:
# To create a package while developing use
# pip-create_package develop
# else just pip-create_package
rm -rf build dist devinstaller.egg-info/ venv
if [ "$1" == "develop" ]; then
    virtualenv -p python3 venv
    venv/bin/python setup.py develop
    venv/bin/pip install -r requirements.txt
else
    python3 setup.py sdist bdist_wheel
fi
